#!/bin/bash

export LOCAL_SRC_DIR="$(pwd)/mywork/src"
export LOCAL_BUILD_DIR="$(pwd)/mywork/build"
export LOCAL_LOG_DIR="$(pwd)/mywork/log"

# # uncomment to have custom variables
# export LOCAL_SRC_DIR=$HOME/THE_PROJECT/mermaid
# export LOCAL_BUILD_DIR=./build
# export LOCAL_LOG_DIR=./log

mkdir -p $LOCAL_SRC_DIR
mkdir -p $LOCAL_BUILD_DIR
mkdir -p $LOCAL_LOG_DIR

touch $LOCAL_LOG_DIR/kroki-client.log